name: Check

on:
  workflow_dispatch:
  push:
    paths:
      - 'CHANGELOG.md'
      - '.aspell.*.pws'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: 'CHANGELOG.md'
  spellchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup aspell
        run: sudo apt-get -y update && sudo apt-get -y install aspell aspell-en
      - name: Run spellchecker
        run: |
          SPELLCHECK_OUT="$(aspell --lang=en --encoding=utf-8 \
            --personal=./.aspell.en.pws list < CHANGELOG.md)"
          printf '%s\n' "$SPELLCHECK_OUT"
          test -z "$SPELLCHECK_OUT"
